### ISSUE TITLE
deploy-local fails without accessKeyId

### ISSUE THREAD

**Issue by Tornquist** [brunomorency/sampic-client#3]
When calling `deploy-local` on a stack and config that was supported in the pre RC version, the following error is thrown: `ERROR: Cannot read property 'accessKeyId' of null`

When deploying the same stack, config, code with the old version it works as expected. 

From what I've read so far `_initAwsCredentials` in `utils.js` requires profile or specific credentials as part of the cmdOpts. 

I think that if nothing is specified, the default behavior should be to use the default credentials and then fallback to null. 

Although, with the way the cloud service is configured, I could see how the desired behavior would be to reject the action. I think that rejection makes sense when using `deploy`, but for a local request I think it's safe to use the profile on the local machine.

**Comment by brunomorency** [comment]
Thanks @Tornquist for the report. I just published 0.7.0-rc.3 with a fix for this.
